export enum Action {
    SEND_ORDER_FOR_SELLERS = '📩 Отправить заказ продавцу',
    BUTTON_MAIN_MENU = '👈 в главное меню',
    VIEW_ORDERS = '💳 Мои заказы',
    SEND_ORDER = '📤 Оформить заказ',
    CONTINUE = '📝 Добавить ещё товар',
    LOGIN = '👤 Авторизация',
    BACK = '👈 Назад',
    MAKE_ORDER = '📤 Оформить заказ',
    MAIN_MENU = '👈 в главное меню',
    FAQ = '💡 FAQ',
    ACCEPT = '✔️ Принять',
    DENY = '❌ Отменить',
    READY_TO_BE_ISSUED = '📦 Готов к выдаче',
    YES_DELETE = 'Да, удалить',
    NO_DELETE = 'Отменить',
    ACCEPTED = 'Окей, принял!',
    INCORRECT_NAME = 'Некорректное название товара',
    INCORRECT_VALUE = 'Некорректное кол-во товара'
};